// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models
{
    public partial class ChiNhanh
    {
        public ChiNhanh()
        {
            Kho = new HashSet<Kho>();
            NhanVien = new HashSet<NhanVien>();
        }

        public string CN_ID { get; set; }
        public string CN_Name { get; set; }
        public string CN_Address { get; set; }
        public string NV_ID { get; set; }

        public virtual NhanVien NV { get; set; }
        public virtual ICollection<Kho> Kho { get; set; }
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}