// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models;

public partial class ChiTietDonNhap
{
    public string Lo_ID { get; set; }

    public string DNhap_ID { get; set; }

    public string Description { get; set; }

    public string Thuoc_ID { get; set; }

    public int? Quantity { get; set; }

    public virtual DonNhap DNhap { get; set; }

    public virtual Lo Lo { get; set; }

    public virtual Thuoc Thuoc { get; set; }
}