// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models
{
    public partial class DonNhap
    {
        public DonNhap()
        {
            ChiTietDonNhaps = new HashSet<ChiTietDonNhap>();
            Thuocs = new HashSet<Thuoc>();
        }

        public string DNhap_ID { get; set; }
        public string NCC_ID { get; set; }
        public string Thuoc_ID { get; set; }
        public DateTime DN_Datetime { get; set; }
        public string DN_Name { get; set; }
        public string NV_ID { get; set; }

        public virtual NCC NCC { get; set; }
        public virtual NhanVien NV { get; set; }
        public virtual Thuoc Thuoc { get; set; }
        public virtual ICollection<ChiTietDonNhap> ChiTietDonNhaps { get; set; }
        public virtual ICollection<Thuoc> Thuocs { get; set; }
    }
}