// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models;

public partial class DonXuat
{
    public string DXuat_ID { get; set; }

    public string DX_Name { get; set; }

    public DateTime DX_Datetime { get; set; }

    public string NV_ID { get; set; }

    public virtual ChiTietDonXuat ChiTietDonXuat { get; set; }

    public virtual NhanVien NV { get; set; }
}