// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models;

public partial class Lo
{
    public string Lo_ID { get; set; }

    public string Lo_Name { get; set; }

    public string Lo_Position { get; set; }

    public string Kho_ID { get; set; }

    public virtual ICollection<ChiTietDonNhap> ChiTietDonNhap { get; set; } = new List<ChiTietDonNhap>();

    public virtual ICollection<ChiTietThuoc> ChiTietThuoc { get; set; } = new List<ChiTietThuoc>();

    public virtual Kho Kho { get; set; }
}