// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models
{
    public partial class Lo
    {
        public Lo()
        {
            ChiTietDonNhaps = new HashSet<ChiTietDonNhap>();
            ChiTietThuocs = new HashSet<ChiTietThuoc>();
        }

        public string Lo_ID { get; set; }
        public string Lo_Name { get; set; }
        public string Lo_Position { get; set; }
        public string Kho_ID { get; set; }

        public virtual Kho Kho { get; set; }
        public virtual ICollection<ChiTietDonNhap> ChiTietDonNhaps { get; set; }
        public virtual ICollection<ChiTietThuoc> ChiTietThuocs { get; set; }
    }
}