// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models;

public partial class NhanVien
{
    public string NV_ID { get; set; }

    public string NV_Name { get; set; }

    public DateTime? BirthDay { get; set; }

    public string Sex { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string CN_ID { get; set; }

    public string UserID { get; set; }

    public virtual ChiNhanh CN { get; set; }

    public virtual ICollection<DonNhap> DonNhap { get; set; } = new List<DonNhap>();

    public virtual ICollection<DonXuat> DonXuat { get; set; } = new List<DonXuat>();

    public virtual TaiKhoan User { get; set; }
}