// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models
{
    public partial class NhomThuoc
    {
        public NhomThuoc()
        {
            Thuocs = new HashSet<Thuoc>();
        }

        public string Nhom_ID { get; set; }
        public string Nhom_Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Thuoc> Thuocs { get; set; }
    }
}