// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models
{
    public partial class Permission
    {
        public Permission()
        {
            Role = new HashSet<Role>();
        }

        public string PermissionID { get; set; }
        public string PermissionName { get; set; }

        public virtual ICollection<Role> Role { get; set; }
    }
}