// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebAPI_QLKH.Models
{
    public partial class QLKH_ThuocContext : DbContext
    {
        public QLKH_ThuocContext()
        {
        }

        public QLKH_ThuocContext(DbContextOptions<QLKH_ThuocContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<ChiTietDonNhap> ChiTietDonNhaps { get; set; }
        public virtual DbSet<ChiTietDonXuat> ChiTietDonXuats { get; set; }
        public virtual DbSet<ChiTietThuoc> ChiTietThuocs { get; set; }
        public virtual DbSet<DonNhap> DonNhaps { get; set; }
        public virtual DbSet<DonXuat> DonXuats { get; set; }
        public virtual DbSet<Kho> Khos { get; set; }
        public virtual DbSet<Lo> Los { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhomThuoc> NhomThuocs { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-CMSGFMS\\HONGAN;Initial Catalog=QLKH_Thuoc;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ChiNhanh>(entity =>
            {
                entity.HasKey(e => e.CN_ID);

                entity.ToTable("ChiNhanh");

                entity.Property(e => e.CN_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.CN_Address).HasMaxLength(50);

                entity.Property(e => e.CN_Name).HasMaxLength(50);

                entity.Property(e => e.NV_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.NV)
                    .WithMany(p => p.ChiNhanhs)
                    .HasForeignKey(d => d.NV_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiNhanh_NhanVien");
            });

            modelBuilder.Entity<ChiTietDonNhap>(entity =>
            {
                entity.HasKey(e => new { e.Lo_ID, e.DNhap_ID });

                entity.ToTable("ChiTietDonNhap");

                entity.Property(e => e.Lo_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.DNhap_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.DNhap)
                    .WithMany(p => p.ChiTietDonNhaps)
                    .HasForeignKey(d => d.DNhap_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietDonNhap_DonNhap");

                entity.HasOne(d => d.Lo)
                    .WithMany(p => p.ChiTietDonNhaps)
                    .HasForeignKey(d => d.Lo_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietDonNhap_Lo");
            });

            modelBuilder.Entity<ChiTietDonXuat>(entity =>
            {
                entity.HasKey(e => new { e.Thuoc_ID, e.DXuat_ID });

                entity.ToTable("ChiTietDonXuat");

                entity.Property(e => e.Thuoc_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.DXuat_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.DXuat)
                    .WithMany(p => p.ChiTietDonXuats)
                    .HasForeignKey(d => d.DXuat_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietDonXuat_DonXuat");

                entity.HasOne(d => d.Thuoc)
                    .WithMany(p => p.ChiTietDonXuats)
                    .HasForeignKey(d => d.Thuoc_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietDonXuat_Thuoc");
            });

            modelBuilder.Entity<ChiTietThuoc>(entity =>
            {
                entity.HasKey(e => new { e.Thuoc_ID, e.Lo_ID });

                entity.ToTable("ChiTietThuoc");

                entity.Property(e => e.Thuoc_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Lo_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.Lo)
                    .WithMany(p => p.ChiTietThuocs)
                    .HasForeignKey(d => d.Lo_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietThuoc_Lo");

                entity.HasOne(d => d.Thuoc)
                    .WithMany(p => p.ChiTietThuocs)
                    .HasForeignKey(d => d.Thuoc_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietThuoc_Thuoc");
            });

            modelBuilder.Entity<DonNhap>(entity =>
            {
                entity.HasKey(e => e.DNhap_ID);

                entity.ToTable("DonNhap");

                entity.Property(e => e.DNhap_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.DN_Datetime).HasColumnType("datetime");

                entity.Property(e => e.DN_Name).HasMaxLength(50);

                entity.Property(e => e.NCC_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.NV_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Thuoc_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.NCC)
                    .WithMany(p => p.DonNhaps)
                    .HasForeignKey(d => d.NCC_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DonNhap_NCC");

                entity.HasOne(d => d.NV)
                    .WithMany(p => p.DonNhaps)
                    .HasForeignKey(d => d.NV_ID)
                    .HasConstraintName("FK_DonNhap_NhanVien");

                entity.HasOne(d => d.Thuoc)
                    .WithMany(p => p.DonNhaps)
                    .HasForeignKey(d => d.Thuoc_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DonNhap_Thuoc");
            });

            modelBuilder.Entity<DonXuat>(entity =>
            {
                entity.HasKey(e => e.DXuat_ID);

                entity.ToTable("DonXuat");

                entity.Property(e => e.DXuat_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.DX_Datetime).HasColumnType("datetime");

                entity.Property(e => e.DX_Name).HasMaxLength(50);

                entity.Property(e => e.NV_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.NV)
                    .WithMany(p => p.DonXuats)
                    .HasForeignKey(d => d.NV_ID)
                    .HasConstraintName("FK_DonXuat_NhanVien");
            });

            modelBuilder.Entity<Kho>(entity =>
            {
                entity.HasKey(e => e.Kho_ID);

                entity.ToTable("Kho");

                entity.Property(e => e.Kho_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.CN_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Kho_Address).HasMaxLength(50);

                entity.Property(e => e.Kho_Name).HasMaxLength(50);

                entity.HasOne(d => d.CN)
                    .WithMany(p => p.Khos)
                    .HasForeignKey(d => d.CN_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Kho_ChiNhanh");
            });

            modelBuilder.Entity<Lo>(entity =>
            {
                entity.HasKey(e => e.Lo_ID);

                entity.ToTable("Lo");

                entity.Property(e => e.Lo_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Kho_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Lo_Name).HasMaxLength(50);

                entity.Property(e => e.Lo_Position).HasMaxLength(50);

                entity.HasOne(d => d.Kho)
                    .WithMany(p => p.Los)
                    .HasForeignKey(d => d.Kho_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Lo_Kho");
            });

            modelBuilder.Entity<NCC>(entity =>
            {
                entity.HasKey(e => e.NCC_ID);

                entity.ToTable("NCC");

                entity.Property(e => e.NCC_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.NCC_Address).HasMaxLength(50);

                entity.Property(e => e.NCC_Name).HasMaxLength(50);

                entity.Property(e => e.Quantity)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            modelBuilder.Entity<NhanVien>(entity =>
            {
                entity.HasKey(e => e.NV_ID);

                entity.ToTable("NhanVien");

                entity.Property(e => e.NV_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Address).HasMaxLength(50);

                entity.Property(e => e.BirthDay).HasColumnType("datetime");

                entity.Property(e => e.CN_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.NV_Name).HasMaxLength(50);

                entity.Property(e => e.Sex)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.UserID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.HasOne(d => d.CN)
                    .WithMany(p => p.NhanViens)
                    .HasForeignKey(d => d.CN_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_NhanVien_ChiNhanh");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.NhanViens)
                    .HasForeignKey(d => d.UserID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_NhanVien_User");
            });

            modelBuilder.Entity<NhomThuoc>(entity =>
            {
                entity.HasKey(e => e.Nhom_ID);

                entity.ToTable("NhomThuoc");

                entity.Property(e => e.Nhom_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Nhom_Name).HasMaxLength(50);
            });

            modelBuilder.Entity<Permission>(entity =>
            {
                entity.ToTable("Permission");

                entity.Property(e => e.PermissionID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.PermissionName).HasMaxLength(50);
            });

            modelBuilder.Entity<Role>(entity =>
            {
                entity.ToTable("Role");

                entity.Property(e => e.RoleID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.RoleName).HasMaxLength(50);

                entity.HasMany(d => d.Permissions)
                    .WithMany(p => p.Roles)
                    .UsingEntity<Dictionary<string, object>>(
                        "Role_Permission",
                        l => l.HasOne<Permission>().WithMany().HasForeignKey("PermissionID").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Role_Permission_Permission"),
                        r => r.HasOne<Role>().WithMany().HasForeignKey("RoleID").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Role_Permission_Role"),
                        j =>
                        {
                            j.HasKey("RoleID", "PermissionID");

                            j.ToTable("Role_Permission");

                            j.IndexerProperty<string>("RoleID").HasMaxLength(10).IsFixedLength();

                            j.IndexerProperty<string>("PermissionID").HasMaxLength(10).IsFixedLength();
                        });
            });

            modelBuilder.Entity<Thuoc>(entity =>
            {
                entity.HasKey(e => e.Thuoc_ID);

                entity.ToTable("Thuoc");

                entity.Property(e => e.Thuoc_ID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.DNhap_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Nhom_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Thuoc_Name).HasMaxLength(50);

                entity.HasOne(d => d.DNhap)
                    .WithMany(p => p.Thuocs)
                    .HasForeignKey(d => d.DNhap_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Thuoc_DonNhap");

                entity.HasOne(d => d.Nhom)
                    .WithMany(p => p.Thuocs)
                    .HasForeignKey(d => d.Nhom_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Thuoc_NhomThuoc");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("User");

                entity.Property(e => e.UserID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.NV_ID)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Password).HasMaxLength(10);

                entity.Property(e => e.RoleID)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.UserName).HasMaxLength(50);

                entity.HasOne(d => d.NV)
                    .WithMany(p => p.Users)
                    .HasForeignKey(d => d.NV_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_User_NhanVien");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.Users)
                    .HasForeignKey(d => d.RoleID)
                    .HasConstraintName("FK_User_Role");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}