// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models
{
    public partial class Role
    {
        public Role()
        {
            User = new HashSet<User>();
            Permission = new HashSet<Permission>();
        }

        public string RoleID { get; set; }
        public string RoleName { get; set; }

        public virtual ICollection<User> User { get; set; }

        public virtual ICollection<Permission> Permission { get; set; }
    }
}