// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models
{
    public partial class Thuoc
    {
        public Thuoc()
        {
            ChiTietDonXuats = new HashSet<ChiTietDonXuat>();
            ChiTietThuocs = new HashSet<ChiTietThuoc>();
            DonNhaps = new HashSet<DonNhap>();
        }

        public string Thuoc_ID { get; set; }
        public string Thuoc_Name { get; set; }
        public string DNhap_ID { get; set; }
        public string Nhom_ID { get; set; }

        public virtual DonNhap DNhap { get; set; }
        public virtual NhomThuoc Nhom { get; set; }
        public virtual ICollection<ChiTietDonXuat> ChiTietDonXuats { get; set; }
        public virtual ICollection<ChiTietThuoc> ChiTietThuocs { get; set; }
        public virtual ICollection<DonNhap> DonNhaps { get; set; }
    }
}