// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI_QLKH.Models;

public partial class Thuoc
{
    public string Thuoc_ID { get; set; }

    public string Thuoc_Name { get; set; }

    public string Nhom_ID { get; set; }

    public virtual ICollection<ChiTietDonNhap> ChiTietDonNhap { get; set; } = new List<ChiTietDonNhap>();

    public virtual ICollection<ChiTietDonXuat> ChiTietDonXuat { get; set; } = new List<ChiTietDonXuat>();

    public virtual ChiTietThuoc ChiTietThuoc { get; set; }

    public virtual NhomThuoc Nhom { get; set; }
}